# Generated by Django 5.0.6 on 2026-02-14 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerApp',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('TECH', 'TECH'), ('HR', 'HR'), ('FINANCE', 'FINANCE'), ('SALES', 'SALES'), ('MARKETING', 'MARKETING'), ('OTHER', 'OTHER')], max_length=100)),
                ('package', models.CharField(choices=[('>3LPA', '>3LPA'), ('3-5LPA', '3-5LPA'), ('5-8LPA', '5-8LPA'), ('8-12LPA', '8-12LPA'), ('12-15LPA', '12-15LPA'), ('>15LPA', '>15LPA')], max_length=100)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('OA', 'Online Assessment'), ('HR', 'HR'), ('TECHNICAL', 'Technical'), ('FINAL', 'Final'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('PLACED', 'Placed')], max_length=100)),
                ('date', models.DateField()),
                ('notes', models.TextField()),
            ],
        ),
    ]
